language: php

php:
  - 5.3
  - 5.4

env:
  - BEHAT_PARAMS="formatter[name]=progress"

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: php bin/behat
